### PR TITLE
Command to either expand a snippet or define it by editting with tmux and vim

### PR DESCRIPTION
**Pull request by talwrii**
You might consider the slightly too niche due to the tmux dependencies. Also I don't know if it detracts a bit from the core purpose of the project

However:
1. I felt that this was kind of useful so I should share it with you
2. I think it's good to at least try to have canonical git repo's, so pull requests are good.

See what you think.

### CODE REVIEW

**Comment by willghatch** [comment]
Sorry for the delay.  I've been super swamped and I'm in the process of moving, so I don't have time to look into this right now, but I will eventually.  Thanks for submitting this patch, despite the fact that I won't look at it for a while!

**Comment by talwrii** [comment]
Hey there,

So I've done a bit more work on this and feel like I might want to do a bit of "marketing":

https://github.com/talwrii/zsh-snippets/commit/5fb355ec3c3105fba4f223beed5c50691f2308e5

I'm not sure what the correct approach is here. I imagine you might not want to be responsible for fixing bugs in all the functionality I've added. One approach is to fork with a rename (with attribution to your project)

Do you have any opinions or preferences regarding this?

Tom

**Comment by willghatch** [comment]
Sorry again for the delay -- I saw the email long ago when I was busy with other things and forgot about it.  I don't think I care to really work on this snippet plugin -- I frankly don't even use it any more (it's still in my config, but I never call the functions).  Go ahead and fork it, with or without attribution or rename -- really all I did was package up stuff that was already floating around on a bunch of web sites.  Your version to interactively add snippets is cooler and much more original than mine, and you shouldn't be waiting for someone as unattentive as me to try to get your version out.

**Comment by talwrii** [comment]
Cool cool. It's okay, I went ahead without waiting ;) -- https://www.youtube.com/watch?v=6bHHKTBNhb0 
Although, people don't seem to have been that interested. I guess I get to appreciate all the productivity gains by myself...

Anyway, I found the existence of this library very useful in terms of i) showing me that this is possible within zsh, ii) giving me a good practical introduction to using zle, iii) allowing me to find pre-existing code as a starting point (one tends to be distrustful that code on forums will actually work and it can take quite a lot of reading to find it, github tends to be rather better indexed).

**Comment by willghatch** [comment]
Well I'm glad it was useful to someone, at least :)

**Pull request closed without merging**
